/**
 * Double-submit CSRF. The BFF sets a readable token cookie at sign-in and rejects
 * any unsafe request whose header does not match it.
 */
export function csrfToken(): string {
  const match = document.cookie.match(/(?:^|;\s*)(?:__Host-)?airev-csrf=([^;]+)/);
  return match?.[1] ?? '';
}

/** fetch() for mutations, with the CSRF header attached. */
export async function mutate(
  path: string,
  init: { method: string; body?: unknown; ifMatch?: number },
): Promise<Response> {
  const headers: Record<string, string> = { 'x-csrf-token': csrfToken() };
  if (init.ifMatch !== undefined) headers['if-match'] = `W/"${init.ifMatch}"`;

  // A file upload has to go as multipart, and the boundary is generated by the
  // browser - setting `content-type` ourselves would produce a header with no
  // boundary and an unparseable request. So FormData is passed through untouched
  // and only JSON gets an explicit content type.
  const isFormData = typeof FormData !== 'undefined' && init.body instanceof FormData;
  if (!isFormData) headers['content-type'] = 'application/json';

  return fetch(path, {
    method: init.method,
    headers,
    credentials: 'same-origin',
    body:
      init.body === undefined
        ? undefined
        : isFormData
          ? (init.body as FormData)
          : JSON.stringify(init.body),
  });
}
